### PR TITLE
Simplify code

### PR DESCRIPTION
**Pull request by darxriggs**
This is all about simplifying code around getting an instance of `Jenkins`.

More details can be found in the commit comments.

### CODE REVIEW

**Comment by Jochen-A-Fuerbacher** [comment]
We're planning to do a release of JobConfigHistory soon. I prefer to merge this PR after the next release.

**Comment by darxriggs** [comment]
That's ok for me. I am already working on another pull request.

**Comment by mfriedenhagen** [comment]
Hello, I think I introduced the indirection because testing gets easier with this

**Comment by darxriggs** [comment]
@mfriedenhagen Have you seen my commit message on b3e06d26768df5548425ccedc9db16f4ac9691a2 regarding the removal of the `Jenkins` instance? What's your opinion on it?

How do we go on with this pull request? Are there objections to not merge it as is?

**Comment by mfriedenhagen** [comment]
@darxriggs, I would always prefer to inject such a dependency but as I am not actively involved in the development anymore, I think @jochen-a-fuerbacher should decide.

**Pull request merged**
