### PR TITLE
Adding LICENSE file to project

### PR DESCRIPTION
**Pull request by kshithijiyer**

### CODE REVIEW

**Comment by stefanbrausch** [comment]
There's a license information in the pom.xml file already. Maybe we should use this copyright information.

**Comment by kshithijiyer** [comment]
It is a requirement to have this file separate as depending on the language and the type of project the pom.xml may or may not be present.

**Comment by stefanbrausch** [comment]
Sure, that's not the question.
But could you add this copyright text instead only Jenkins?
 ~ Copyright (c) 2010-2019, Stefan Brausch, Mirko Friedenhagen, Jochen A. Fuerbacher,
 ~ Kathi Stutz, Yordan Boev, Robin R. Schulz

**Comment by kshithijiyer** [comment]
> Sure, that's not the question.
> But could you add this copyright text instead only Jenkins?
> ~ Copyright (c) 2010-2019, Stefan Brausch, Mirko Friedenhagen, Jochen A. Fuerbacher,
> ~ Kathi Stutz, Yordan Boev, Robin R. Schulz
Done

**Comment by stefanbrausch** [comment]
Thanks :-)

**Pull request merged**
