### PR TITLE
Reduce deprecated API usage

### PR DESCRIPTION
**Pull request by darxriggs**

### CODE REVIEW

**Comment by Jochen-A-Fuerbacher** [comment]
@darxriggs This pull request breaks some tests. Please look at them.

**Comment by darxriggs** [comment]
Thanks. I am already at it.

**Comment by darxriggs** [comment]
@Jochen-A-Fuerbacher Tests are fixed now.

**Comment by Jochen-A-Fuerbacher** [comment]
Looks good, thanks!

**Pull request merged**
