### PR TITLE
[JEP-227] Prepare plugin for Acegi update

### PR DESCRIPTION
**Pull request by Wadeck**
Related to https://github.com/jenkinsci/jep/pull/306/ and https://github.com/jenkinsci/jenkins/pull/4848

No fundamental functional change, just consistency + different approach to prevent issue with Acegi related classes.

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Comment by akoeplinger** [comment]
I saw this PR is listed as a prerequisite for Jenkins 2.277.1 on https://github.com/jenkinsci/jep/blob/master/jep/227/compatibility.adoc, can it be merged?

**Comment by jglick** [comment]
It is likely not a hard prerequisite for upgrading Jenkins core, but certainly recommended for this to be released. ping @Jochen-A-Fuerbacher

**Comment by jglick** [comment]
@Jochen-A-Fuerbacher please https://github.com/jenkinsci/jep/edit/master/jep/227/compatibility.adoc whenever this is released.

**Comment by Jochen-A-Fuerbacher** [comment]
@jglick done.

**Pull request merged**
