### PR TITLE
Alter module visibility to facilitate package separation.

### PR DESCRIPTION
**Pull request by bdkoepke**
Attempting to find module boundaries by separating FileHistoryDao and it's dependencies into a separate package.

The current files that I believe are part of the 'File' backend and not the jobConfigHistory central package are:

ConfigInfoCollector
DeletedFileFilter
FileHistoryDao
HistoryDescrToConfigInfo
HistoryFileFilter
JobConfigHistoryPurger
JobConfigHistoryRootAction?
JobConfigHistoryProjectAction?
NonDeletedFileFilter
Purgeable

Before merging this request I would like some feedback into which of these should actually be part of the main file backend and which should be part of the central jobConfigHistory interface. Once that is done I will do the remaining work to separate the packages correctly.

### CODE REVIEW

**Comment by Jochen-A-Fuerbacher** [comment]
Have you looked at `ComputerConfigHistoryAction#getFile`? I think that could also be part of the File backend.

**Comment by mfriedenhagen** [comment]
@bdkoepke, right now you only widened the visibility, right? And want to create a new package `filehistorydao`? Great, after introducing the unit tests I was somewhat exhausted, so go for it!

**Comment by bdkoepke** [comment]
Hello,

Sorry for the delay, a higher priority project came up and I was pulled off of this temporarily.

I will take a look at ComputerConfigHistoryAction.

@mfriedenhagen Yes I widened visibility at the moment. There are two classes that I found to be 'sticky' in that they aren't easily removed from their current package. Those are JobConfigHistoryRootAction and JobConfigHistoryProjectAction. Should those be part of the jobConfigHistory base plugin or part of the file backend? I was able to move them but once I did that it broke some of the tests.

**Comment by Jochen-A-Fuerbacher** [comment]
Hello @bdkoepke,

`JobConfigHistoryRootAction`and `JobConfigHistoryProjectAction` are Actions, so I think these classes should be part of the base and not of the file backend.
Do you want to create a file backend package? Otherwise I'll merge your current pull request.

**Pull request merged**
